const hours = [
  { realTime: "00:00", id: 0, toggled: false, time: "0" },
  { realTime: "00:30", id: 1, toggled: false, time: "" },
  { realTime: "01:00", id: 2, toggled: false, time: "1" },
  { realTime: "01:30", id: 3, toggled: false, time: "" },
  { realTime: "02:00", id: 4, toggled: false, time: "2" },
  { realTime: "02:30", id: 5, toggled: false, time: "" },
  { realTime: "03:00", id: 6, toggled: false, time: "3" },
  { realTime: "03:30", id: 7, toggled: false, time: "" },
  { realTime: "04:00", id: 8, toggled: false, time: "4" },
  { realTime: "04:30", id: 9, toggled: false, time: "" },
  { realTime: "05:00", id: 10, toggled: false, time: "5" },
  { realTime: "05:30", id: 11, toggled: false, time: "" },
  { realTime: "06:00", id: 12, toggled: false, time: "6" },
  { realTime: "06:30", id: 13, toggled: false, time: "" },
  { realTime: "07:00", id: 14, toggled: false, time: "7" },
  { realTime: "07:30", id: 15, toggled: false, time: "" },
  { realTime: "08:00", id: 16, toggled: false, time: "8" },
  { realTime: "08:30", id: 17, toggled: false, time: "" },
  { realTime: "09:00", id: 18, toggled: false, time: "9" },
  { realTime: "09:30", id: 19, toggled: false, time: "" },
  { realTime: "10:00", id: 20, toggled: false, time: "10" },
  { realTime: "10:30", id: 21, toggled: false, time: "" },
  { realTime: "11:00", id: 22, toggled: false, time: "11" },
  { realTime: "11:30", id: 23, toggled: false, time: "" },
  { realTime: "12:00", id: 24, toggled: false, time: "12" },
  { realTime: "12:30", id: 25, toggled: false, time: "" },
  { realTime: "13:00", id: 26, toggled: false, time: "13" },
  { realTime: "13:30", id: 27, toggled: false, time: "" },
  { realTime: "14:00", id: 28, toggled: false, time: "14" },
  { realTime: "14:30", id: 29, toggled: false, time: "" },
  { realTime: "15:00", id: 30, toggled: false, time: "15" },
  { realTime: "15:30", id: 31, toggled: false, time: "" },
  { realTime: "16:00", id: 32, toggled: false, time: "16" },
  { realTime: "16:30", id: 33, toggled: false, time: "" },
  { realTime: "17:00", id: 34, toggled: false, time: "17" },
  { realTime: "17:30", id: 35, toggled: false, time: "" },
  { realTime: "18:00", id: 36, toggled: false, time: "18" },
  { realTime: "18:30", id: 37, toggled: false, time: "" },
  { realTime: "19:00", id: 38, toggled: false, time: "19" },
  { realTime: "19:30", id: 39, toggled: false, time: "" },
  { realTime: "20:00", id: 40, toggled: false, time: "20" },
  { realTime: "20:30", id: 41, toggled: false, time: "" },
  { realTime: "21:00", id: 42, toggled: false, time: "21" },
  { realTime: "21:30", id: 43, toggled: false, time: "" },
  { realTime: "22:00", id: 44, toggled: false, time: "22" },
  { realTime: "22:30", id: 45, toggled: false, time: "" },
  { realTime: "23:00", id: 46, toggled: false, time: "23" },
  { realTime: "23:30", id: 47, toggled: false, time: "" },
  // 다음날 - 새벽 고려
  { id: 48, toggled: false, time: "0" },
  { id: 49, toggled: false, time: "" },
  { id: 50, toggled: false, time: "1" },
  { id: 51, toggled: false, time: "" },
  { id: 52, toggled: false, time: "2" },
  { id: 53, toggled: false, time: "" },
  { id: 54, toggled: false, time: "3" },
  { id: 55, toggled: false, time: "" },
  { id: 56, toggled: false, time: "4" },
  { id: 57, toggled: false, time: "" },
  { id: 58, toggled: false, time: "5" },
  { id: 59, toggled: false, time: "" },
  { id: 60, toggled: false, time: "6" },
  { id: 61, toggled: false, time: "" },
  { id: 62, toggled: false, time: "7" },
  { id: 63, toggled: false, time: "" },
  { id: 64, toggled: false, time: "8" },
  { id: 65, toggled: false, time: "" },
  { id: 66, toggled: false, time: "9" },
  { id: 67, toggled: false, time: "" },
  { id: 68, toggled: false, time: "10" },
  { id: 69, toggled: false, time: "" },
  { id: 70, toggled: false, time: "11" },
  { id: 71, toggled: false, time: "" },
  { id: 72, toggled: false, time: "12" },
  { id: 73, toggled: false, time: "" },
  { id: 74, toggled: false, time: "13" },
  { id: 75, toggled: false, time: "" },
  { id: 76, toggled: false, time: "14" },
  { id: 77, toggled: false, time: "" },
  { id: 78, toggled: false, time: "15" },
  { id: 79, toggled: false, time: "" },
  { id: 80, toggled: false, time: "16" },
  { id: 81, toggled: false, time: "" },
  { id: 82, toggled: false, time: "17" },
  { id: 83, toggled: false, time: "" },
  { id: 84, toggled: false, time: "18" },
  { id: 85, toggled: false, time: "" },
  { id: 86, toggled: false, time: "19" },
  { id: 87, toggled: false, time: "" },
  { id: 88, toggled: false, time: "20" },
  { id: 89, toggled: false, time: "" },
  { id: 90, toggled: false, time: "21" },
  { id: 91, toggled: false, time: "" },
  { id: 92, toggled: false, time: "22" },
  { id: 93, toggled: false, time: "" },
  { id: 94, toggled: false, time: "23" },
  { id: 95, toggled: false, time: "" },
  { id: 96, toggled: false, time: "24" },

];

export default hours;
